[build]
  command = "npm install"
  functions = "functions/"
  publish = "public/"

[functions."api"]
  included_files = ["views/**", "routes/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200